name: shrugger
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.13
  - pip

  # Torch (CPU by default). If you need CUDA, see note below.
  - pytorch

  # Hugging Face + NLP utils
  - transformers
  - tokenizers
  - datasets
  - accelerate
  - safetensors
  - sentencepiece

  # Numerics & plotting
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pyyaml
  - requests

  # Notebooks
  - jupyterlab
  - ipykernel
  - ipywidgets

  # Dev tooling
  - black
  - ruff
  - pytest
  - pytest-cov

  - pip:
    - black[jupyter]
    - -e .